### ISSUE TITLE
corners square

### ISSUE THREAD

**Issue by joaonetoeng** [GarryBGoode/Manim_CAD_Drawing_utils#1]
![image](https://user-images.githubusercontent.com/28939222/215275955-141bd0a4-c1ca-4e92-9b16-bedd25c7319b.png)

Would you help me. how to create a dimension taking the corners of the 4 points of the square?

**Comment by GarryBGoode** [comment]
The Linear_Dimension takes the 'start' and 'end' points, those define the lines to be measured, there are many ways to put it where you want it, it is kind of manual and depends on circumstances.

This one puts a dimension on every curve piece (side).

class test0(Scene):
    def construct(self):
        mob1 = Square()
        Dim_grp = VGroup()
        for i in range(mob1.get_num_curves()):
            Dim_grp.add(Linear_Dimension(mob1.get_nth_curve_points(i)[0,:],
                                         mob1.get_nth_curve_points(i)[3,:],
                                         offset=-1,
                                         color=RED))
        self.add(mob1,Dim_grp)
![test0_ManimCE_v0 16 0 post0](https://user-images.githubusercontent.com/95878914/215276737-eaa41b72-c911-43b1-b0fc-b562eefe3b61.png)

**Comment by joaonetoeng** [comment]
Thank you very much ;)

**Comment by joaonetoeng** [comment]
![image](https://user-images.githubusercontent.com/28939222/215278382-7935e412-8bf9-4052-a5f8-e6991a848f91.png)

Sorry for the inconvenience, but how could I do just one dimension, if I use the for loop ??

**Comment by GarryBGoode** [comment]
Well, you can remove the for loop, and instead of i, just put a number
there. Like

Linear_Dimension(mob1.get_nth_curve_points(2)[0,:],
                 mob1.get_nth_curve_points(2)[3,:],
                 offset=-1,
                 color=RED)


joaonetoeng ***@***.***> ezt írta (időpont: 2023. jan. 28.,
Szo, 17:44):

**Comment by GarryBGoode** [comment]
Ok I'll close this now
